### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by aminsmartsense** [ExodusMovement/format-num#1]
Hello @jprichardson,
 
I am trying to implement this demo but not working in my project. can you help me in this with demo please?

Thanks

**Comment by jprichardson** [comment]
Hi, what is not working? Is the example code not working?

**Comment by aminsmartsense** [comment]
@jprichardson Don't know how to work this code. I have trying but not shown any output.

**Comment by jprichardson** [comment]
Please paste example code, otherwise closed.

**Comment by aminsmartsense** [comment]
@jprichardson I have used same code as per this document. no need to code here.
