### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aminsmartsense** [ExodusMovement/format-num#3]

**Comment by jprichardson** [comment]
Will you post reproducible code?

It's working per this example:

https://runkit.com/58e405ebb4ae70001445ac23/58ec52356d82760014d56cdc

**Comment by gmlnchv** [comment]
Currency formatting doesn't seem to work as per this https://runkit.com/gmlnchv/5912e7300c372b00127766d7

**Comment by RyanZim** [comment]
`format-num` overrides to `style: 'decimal'`: https://github.com/ExodusMovement/format-num/blob/ebf9ab8890a8d9cab780bfba6675cf17d5467904/index.js#L29
